window.sr = ScrollReveal({ reset: true });
sr.reveal(".cabecalho", { duration: 2000 });

window.sr = ScrollReveal({ reset: true });

sr.reveal(".secao__principal__titulo", {duration: 2000});
sr.reveal(".secao__principal__texto", {duration: 2000});
sr.reveal(".secao__secundaria", { rotate: { x: 0, y: 90, z: 0 }, duration: 2000 });
sr.reveal(".secao__secundaria__titulo", { rotate: { x: 0, y: 90, z: 0 }, duration: 2000 });
sr.reveal(".secao__secundaria__texto", { reset: true, duration: 2000 });
sr.reveal(".sobre_nos_imagem", { rotate: { x: 0, y: 90, z: 0 }, duration: 2000, delay: 600 });
sr.reveal(".secao__secundaria__container__dados__individual", { rotate: { x: 0, y: 90, z: 0 }, duration: 2000, delay: 600 });
sr.reveal(".etapas__filtracao__container", { reset: true, duration: 2000, delay:600});
sr.reveal(".swiper", { reset: true, duration: 2000, delay:600});
sr.reveal(".secao__secundaria__integrante", { reset: true, duration: 2000});

window.sr = ScrollReveal({ reset: true });
sr.reveal(".first_section_documentario_title", { duration: 2000, reset: true});
sr.reveal(".first_section_documentario_subtitle", { duration: 2000, delay: 3100, reset: false});
sr.reveal(".first_paragraph_documentario", { reset: true, duration: 2000 });
sr.reveal(".second_section_documentario", { rotate: { x: 0, y: 90, z: 0 }, duration: 2000, delay: 600 });
sr.reveal(".second_section_documentario_title", { reset: true, duration: 2000, delay: 300 });
sr.reveal(".first_section_title", { rotate: { x: 0, y: 90, z: 0 }, duration: 2200 });
sr.reveal(".first_section_subtitle", { reset: true, duration: 2500 });
sr.reveal(".swiper", { rotate: { x: 0, y: 90, z: 0 }, duration: 2000});
sr.reveal(".first_paragraph", { reset: true, duration: 2500 });
sr.reveal(".second_section", { rotate: { x: 0, y: 90, z: 0 }, duration: 2000 });
sr.reveal(".second_section_title", { reset: true, duration: 2000, delay: 500 });
sr.reveal(".list_items", { rotate: { x: 0, y: 90, z: 0 }, duration: 2000, delay: 600 });
sr.reveal(".third_section", { rotate: { x: 0, y: 90, z: 0 }, duration: 2000});
sr.reveal(".diseases_title", { reset: true, duration: 2500, delay: 400});
sr.reveal(".diseases_paragraph", { reset: true, duration: 2500, delay: 500});
sr.reveal(".fourth_section_title", { reset: true, duration: 2000});
sr.reveal(".diseases_items", { rotate: { x: 0, y: 90, z: 0 }, duration: 1500, delay: 500 });
sr.reveal(".curiosities", { rotate: { x: 0, y: 90, z: 0 }, duration: 1500,});
sr.reveal(".curiosities_list_item", { reset: true, duration: 2500, delay: 700});
sr.reveal(".first_section_cartilha__hq", { reset: true, duration: 2000 });
sr.reveal(".first_section_cartilha__hq_title", { reset: true, rotate: { x: 0, y: 90, z: 0 }, duration: 2000 });
sr.reveal(".first_section_cartilha__hq_subtitle", { reset: true, duration: 2000, delay: 400 });
sr.reveal(".second_section_cartilha__hq", { rotate: { x: 0, y: 90, z: 0 }, duration: 1500,});
sr.reveal(".flipbook__cartilha", { rotate: { x: 0, y: 90, z: 0 }, duration: 1500, delay: 400});
sr.reveal(".baixar__cartilha", { reset: true, duration: 2500, delay: 500});
sr.reveal(".rodape", { reset: true, duration: 2000});